### ISSUE TITLE
options to submit CSV or JSON

### ISSUE THREAD

**Issue by davidawad** [KiranJKurian/RUScheduler#8]
I should be able to submit a file with the course section numbers if I want instead of navigating the GUI. 

for example, I'm taking courses defined in the following CSV. 

``` csv
06483,
08150,
14797
...
```

Do you have the capabilities to do a course lookup based on this? It would totally be :100:

**Comment by KiranJKurian** [comment]
Unfortunately with the Rutgers API I am accessing, it would be impractical to do such a thing as I first have to specify what information I wish to receive by subject.
